sorting data by single columns

In [2]:
import pandas as pd

In [4]:
df =pd.read_csv("../data/cars.csv")
df.head(5)

,car name,mpg,cylinders,displacement,horsepower,acceleration,model year,origin
0,chevrolet chevelle malibu,18.0,8,307.0,130,12.0,70,USA
1,buick skylark 320,15.0,8,350.0,165,11.5,70,USA
2,plymouth satellite,18.0,8,318.0,150,11.0,70,USA
3,amc rebel sst,16.0,8,304.0,150,12.0,70,USA
4,ford torino,17.0,8,302.0,140,10.5,70,USA

In [ ]:
df.sort_values(by = 'car name' ).head(10)

,car name,mpg,cylinders,displacement,horsepower,acceleration,model year,origin
96,amc ambassador brougham,13.0,8,360.0,175,11.0,73,USA
9,amc ambassador dpl,15.0,8,390.0,190,8.5,70,USA
66,amc ambassador sst,17.0,8,304.0,150,11.5,72,USA
315,amc concord,24.3,4,151.0,90,20.1,80,USA
257,amc concord,19.4,6,232.0,90,17.2,78,USA
261,amc concord d/l,18.1,6,258.0,120,15.1,78,USA
374,amc concord dl,23.0,4,151.0,?,20.5,82,USA
283,amc concord dl 6,20.2,6,232.0,90,18.2,79,USA
107,amc gremlin,18.0,6,232.0,100,15.0,73,USA
33,amc gremlin,19.0,6,232.0,100,13.0,71,USA

In [ ]:
df.sort_values(by = 'car name',ascending=False ).head(10)

In [ ]:
df.sort_values(by = 'mpg')

2. sorting rows by all columns

In [8]:
df.sort_values(by = ['mpg','displacement'],ascending=[True,False])

,car name,mpg,cylinders,displacement,horsepower,acceleration,model year,origin
28,hi 1200d,9.0,8,304.0,193,18.5,70,USA
25,ford f250,10.0,8,360.0,215,14.0,70,USA
26,chevy c20,10.0,8,307.0,200,15.0,70,USA
67,mercury marquis,11.0,8,429.0,208,11.0,72,USA
103,chevrolet impala,11.0,8,400.0,150,14.0,73,USA
...,...,...,...,...,...,...,...,...
326,vw dasher (diesel),43.4,4,90.0,48,23.7,80,IND
394,vw pickup,44.0,4,97.0,52,24.6,82,IND
325,vw rabbit c (diesel),44.3,4,90.0,48,21.7,80,IND
329,honda civic 1500 gl,44.6,4,91.0,67,13.8,80,ERUOPE
322,mazda glc,46.6,4,86.0,65,17.9,80,ERUOPE

3.prioriting null values

In [13]:
df.sort_values(by ='car name',ascending = False,na_position='first')

,car name,mpg,cylinders,displacement,horsepower,acceleration,model year,origin
293,vw rabbit custom,31.9,4,89.0,71,14.0,79,IND
325,vw rabbit c (diesel),44.3,4,90.0,48,21.7,80,IND
197,vw rabbit,29.0,4,90.0,70,14.2,76,IND
309,vw rabbit,41.5,4,98.0,76,14.7,80,IND
394,vw pickup,44.0,4,97.0,52,24.6,82,IND
...,...,...,...,...,...,...,...,...
315,amc concord,24.3,4,151.0,90,20.1,80,USA
257,amc concord,19.4,6,232.0,90,17.2,78,USA
66,amc ambassador sst,17.0,8,304.0,150,11.5,72,USA
9,amc ambassador dpl,15.0,8,390.0,190,8.5,70,USA
96,amc ambassador brougham,13.0,8,360.0,175,11.0,73,USA

In [12]:
df.columns

Index(['car name', 'mpg', 'cylinders', 'displacement', 'horsepower',
       'acceleration', 'model year', 'origin'],
      dtype='str')