In [9]:
import pandas as pd
df =pd.read_csv("../data/cars.csv")
df.head()

,car name,mpg,cylinders,displacement,horsepower,acceleration,model year,origin
0,chevrolet chevelle malibu,18.0,8,307.0,130,12.0,70,USA
1,buick skylark 320,15.0,8,350.0,165,11.5,70,USA
2,plymouth satellite,18.0,8,318.0,150,11.0,70,USA
3,amc rebel sst,16.0,8,304.0,150,12.0,70,USA
4,ford torino,17.0,8,302.0,140,10.5,70,USA

In [18]:
pd.set_option('display.max_rows',10)

In [19]:
df.loc[((df['origin'] == 'USA') | (df['origin'] == 'IND')) & (df['cylinders'] == 4)]

,car name,mpg,cylinders,displacement,horsepower,acceleration,model year,origin
19,volkswagen 1131 deluxe sedan,26.0,4,97.0,46,20.5,70,IND
20,peugeot 504,25.0,4,110.0,87,17.5,70,IND
21,audi 100 ls,24.0,4,107.0,90,14.5,70,IND
22,saab 99e,25.0,4,104.0,95,17.5,70,IND
23,bmw 2002,26.0,4,121.0,113,12.5,70,IND
...,...,...,...,...,...,...,...,...
393,ford mustang gl,27.0,4,140.0,86,15.6,82,USA
394,vw pickup,44.0,4,97.0,52,24.6,82,IND
395,dodge rampage,32.0,4,135.0,84,11.6,82,USA
396,ford ranger,28.0,4,120.0,79,18.6,82,USA
397,chevy s-10,31.0,4,119.0,82,19.4,82,USA