Absolute path

In [2]:
import pandas as pd

In [7]:
df = pd.read_csv(r'C:\Users\karth\OneDrive\Desktop\datasets\SuperMarket Analysis.csv')
print(df)

      Invoice ID Branch       City Customer type  Gender  \
0    750-67-8428   Alex     Yangon        Member  Female
1    226-31-3081   Giza  Naypyitaw        Normal  Female
2    631-41-3108   Alex     Yangon        Normal  Female
3    123-19-1176   Alex     Yangon        Member  Female
4    373-73-7910   Alex     Yangon        Member  Female
..           ...    ...        ...           ...     ...
995  233-67-5758   Giza  Naypyitaw        Normal    Male
996  303-96-2227  Cairo   Mandalay        Normal  Female
997  727-02-1313   Alex     Yangon        Member    Male
998  347-56-2442   Alex     Yangon        Normal    Male
999  849-09-3807   Alex     Yangon        Member  Female

               Product line  Unit price  Quantity   Tax 5%      Sales  \
0         Health and beauty       74.69         7  26.1415   548.9715
1    Electronic accessories       15.28         5   3.8200    80.2200
2        Home and lifestyle       46.33         7  16.2155   340.5255
3         Health and beauty       58.22         8  23.2880   489.0480
4         Sports and travel       86.31         7  30.2085   634.3785
..                      ...         ...       ...      ...        ...
995       Health and beauty       40.35         1   2.0175    42.3675
996      Home and lifestyle       97.38        10  48.6900  1022.4900
997      Food and beverages       31.84         1   1.5920    33.4320
998      Home and lifestyle       65.82         1   3.2910    69.1110
999     Fashion accessories       88.34         7  30.9190   649.2990

          Date         Time      Payment    cogs  gross margin percentage  \
0     1/5/2019   1:08:00 PM      Ewallet  522.83                 4.761905
1     3/8/2019  10:29:00 AM         Cash   76.40                 4.761905
2     3/3/2019   1:23:00 PM  Credit card  324.31                 4.761905
3    1/27/2019   8:33:00 PM      Ewallet  465.76                 4.761905
4     2/8/2019  10:37:00 AM      Ewallet  604.17                 4.761905
..         ...          ...          ...     ...                      ...
995  1/29/2019   1:46:00 PM      Ewallet   40.35                 4.761905
996   3/2/2019   5:16:00 PM      Ewallet  973.80                 4.761905
997   2/9/2019   1:22:00 PM         Cash   31.84                 4.761905
998  2/22/2019   3:33:00 PM         Cash   65.82                 4.761905
999  2/18/2019   1:28:00 PM         Cash  618.38                 4.761905

     gross income  Rating
0         26.1415     9.1
1          3.8200     9.6
2         16.2155     7.4
3         23.2880     8.4
4         30.2085     5.3
..            ...     ...
995        2.0175     6.2
996       48.6900     4.4
997        1.5920     7.7
998        3.2910     4.1
999       30.9190     6.6

[1000 rows x 17 columns]

In [ ]:
df =pd.read_csv("data/patients.csv")
df

In [6]:
df = pd.read_clipboard()
df

  First name   Last name  Age Gender
0       Tinu    Elejogun   14      F
1     Javier      Zapata   28      M
2       Lily   McGarrett   18      F
3  Olatunkbo    Chijiaku   22      M
4   Adrienne    Anthoula   22      M
5     Axelia  Athanasios   22      M
6  Jon-Kabat        Zinn   22      M
7    Thabang       Mosoa   15      F
8      Rhian       Ellis   12      M

In [12]:
# !pip install openpyxl
import pandas as pd
df =pd.read_excel(r'C:\Users\karth\OneDrive\Desktop\datasets\Sample - Superstore.xlsx',sheet_name='People')
df

              Person   Region
0      Anna Andreadi     West
1        Chuck Magee     East
2     Kelly Williams  Central
3  Cassandra Brandow    South