In [1]:
import pandas as pd

In [ ]:
A = pd.DataFrame([
                  [1,2,3],
                  [4,5,6],
                  [7,8,9]
                  ])
A

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [5]:
B = pd.DataFrame([
                  [1,2],
                  [3,4],
                  [5,6]])
B

   0  1
0  1  2
1  3  4
2  5  6

In [6]:
A.dot(B)

    0    1
0  22   28
1  49   64
2  76  100