In [1]:
import pandas as pd

In [2]:
df= pd.read_csv("../data/cars.csv")
df.head()

,car name,mpg,cylinders,displacement,horsepower,acceleration,model year,origin
0,chevrolet chevelle malibu,18.0,8,307.0,130,12.0,70,USA
1,buick skylark 320,15.0,8,350.0,165,11.5,70,USA
2,plymouth satellite,18.0,8,318.0,150,11.0,70,USA
3,amc rebel sst,16.0,8,304.0,150,12.0,70,USA
4,ford torino,17.0,8,302.0,140,10.5,70,USA

In [4]:
# Fing the maximum horsepower based on origin
df['horsepower'].groupby(df['origin']).max()

origin
ERUOPE    97
IND        ?
USA        ?
Name: horsepower, dtype: str

In [5]:
df['origin'].value_counts()

origin
USA       249
ERUOPE     79
IND        70
Name: count, dtype: int64

,car name,mpg,cylinders,displacement,horsepower,acceleration,model year,origin
19,volkswagen 1131 deluxe sedan,26.0,4,97.0,46,20.5,70,IND
20,peugeot 504,25.0,4,110.0,87,17.5,70,IND
21,audi 100 ls,24.0,4,107.0,90,14.5,70,IND
22,saab 99e,25.0,4,104.0,95,17.5,70,IND
23,bmw 2002,26.0,4,121.0,113,12.5,70,IND
...,...,...,...,...,...,...,...,...
354,renault 18i,34.5,4,100.0,?,15.8,81,IND
359,peugeot 505s turbo diesel,28.1,4,141.0,80,20.4,81,IND
360,volvo diesel,30.7,6,145.0,76,19.6,81,IND
375,volkswagen rabbit l,36.0,4,105.0,74,15.3,82,IND
394,vw pickup,44.0,4,97.0,52,24.6,82,IND